"""Change exercise_id and workout_id to string for custom workouts

Revision ID: 2aa036d7f694
Revises: 20260125100227
Create Date: 2026-01-26 15:36:20.606858

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2aa036d7f694'
down_revision: Union[str, Sequence[str], None] = '20260125100227'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('payments', 'status',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Enum('PENDING', 'SUCCEEDED', 'FAILED', 'REFUNDED', name='paymentstatus', native_enum=False),
               existing_nullable=False)
    op.alter_column('subscriptions', 'tier',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Enum('FREE', 'PREMIUM', 'ENTERPRISE', name='subscriptiontier', native_enum=False),
               existing_nullable=False)
    op.alter_column('subscriptions', 'status',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Enum('ACTIVE', 'CANCELED', 'PAST_DUE', 'TRIALING', 'EXPIRED', name='subscriptionstatus', native_enum=False),
               existing_nullable=False)
    op.drop_constraint(op.f('uq_user_achievement'), 'user_achievements', type_='unique')
    op.drop_index(op.f('ix_workout_sessions_status'), table_name='workout_sessions')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_workout_sessions_status'), 'workout_sessions', ['status'], unique=False)
    op.create_unique_constraint(op.f('uq_user_achievement'), 'user_achievements', ['user_id', 'achievement_id'], postgresql_nulls_not_distinct=False)
    op.alter_column('subscriptions', 'status',
               existing_type=sa.Enum('ACTIVE', 'CANCELED', 'PAST_DUE', 'TRIALING', 'EXPIRED', name='subscriptionstatus', native_enum=False),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
    op.alter_column('subscriptions', 'tier',
               existing_type=sa.Enum('FREE', 'PREMIUM', 'ENTERPRISE', name='subscriptiontier', native_enum=False),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
    op.alter_column('payments', 'status',
               existing_type=sa.Enum('PENDING', 'SUCCEEDED', 'FAILED', 'REFUNDED', name='paymentstatus', native_enum=False),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
    # ### end Alembic commands ###
