"""Change exercise_id and workout_id columns to string

Revision ID: c28b4abf6b77
Revises: 2aa036d7f694
Create Date: 2026-01-26 15:44:51.815818

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c28b4abf6b77'
down_revision: Union[str, Sequence[str], None] = '2aa036d7f694'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Drop constraints FIRST
    op.drop_constraint('exercise_sets_exercise_id_fkey', 'exercise_sets', type_='foreignkey')
    op.drop_constraint('workout_sessions_workout_id_fkey', 'workout_sessions', type_='foreignkey')
    
    # Then alter columns with explicit casting
    op.alter_column('exercise_sets', 'exercise_id',
               existing_type=sa.UUID(),
               type_=sa.String(length=255),
               existing_nullable=True,
               postgresql_using='exercise_id::varchar')
               
    op.alter_column('workout_sessions', 'workout_id',
               existing_type=sa.UUID(),
               type_=sa.String(length=255),
               existing_nullable=True,
               postgresql_using='workout_id::varchar')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(op.f('workout_sessions_workout_id_fkey'), 'workout_sessions', 'workouts', ['workout_id'], ['id'], ondelete='SET NULL')
    op.alter_column('workout_sessions', 'workout_id',
               existing_type=sa.String(length=255),
               type_=sa.UUID(),
               existing_nullable=True)
    op.create_foreign_key(op.f('exercise_sets_exercise_id_fkey'), 'exercise_sets', 'exercises', ['exercise_id'], ['id'], ondelete='SET NULL')
    op.alter_column('exercise_sets', 'exercise_id',
               existing_type=sa.String(length=255),
               type_=sa.UUID(),
               existing_nullable=True)
    # ### end Alembic commands ###
